### ISSUE TITLE
DST error on datetimes when reading from Cassandra into Sparklyr

### ISSUE THREAD

**Issue by AkhilNairAmey** [rstudio/sparklyr#1056]
When reading a date from Cassandra into spark using `sparklyr_0.7.0-9035` (current version of master), DST (I assume) pushes the date back by one day.  This can prove costly if things end up being partitioned wrongly because of it.

This is not a problem on the current CRAN version of `sparklyr`

```
> installed.packages()["sparklyr",]["Version"]
     Version 
"0.7.0-9035" 
```

### Reproducible example

Set up keyspace and table in Cassandra
```
CREATE KEYSPACE "dst_bug"
WITH replication = {'class': 'SimpleStrategy', 'replication_factor' : 1} ;

CREATE TABLE dst_bug.tbl (
    dttm date,
    PRIMARY KEY (dttm)
) ;
```

```
library(sparklyr)
library(dplyr)
library(crassy)  # remotes::install_github("AkhilNairAmey/crassy")  # some helper bindings

config <- spark_config()
config$sparklyr.defaultPackages = "com.datastax.spark:spark-cassandra-connector_2.11:2.0.5"
config$spark.cassandra.connection.host = 'localhost'

sc <- spark_connect(
  master     = 'local', 
  version = "2.0.2",
  config = config
)

# Make some data
handle = copy_to(sc, tibble(dttm = as.Date("2017-05-13")), "spk_tbl")

# Insert into keyspace.tbl
crassy::spark_write_cassandra_table(handle, "dst_bug", "tbl")

# Read back data
crassy::spark_load_cassandra_table(sc, "dst_bug", "tbl", "read_spk_tbl")
```

Resulting in
```
> crassy::spark_load_cassandra_table(sc, "dst_bug", "tbl", "read_spk_tbl")
# Source:   table<read_spk_tbl> [?? x 1]
# Database: spark_connection
        dttm
      <date>
1 2017-05-12
```
where the date has shifted from `2017-05-13` to `2017-05-12`.

**Comment by javierluraschi** [comment]
@AkhilNairAmey Do you happen to know if this is also a problem if you insert the data directly in Cassandra?

**Comment by AkhilNairAmey** [comment]
I don't off the bat, I can check in a couple hours.

**Comment by AkhilNairAmey** [comment]
@javierluraschi Still a problem when inserting data directly into Cassandra

**Comment by javierluraschi** [comment]
@AkhilNairAmey looks fixed in latest devel version. However, rather than using `copy_to` I'm using `spark_apply()`. The problem with `copy_to()` is that is does not yet fully support date/times and copying large datasets so it should be avoided in most cases. Most clusters already have data in them so `copy_to()` is usually used in prototypes, etc and less on production environments with data that spans over the entire clusters.

Anyways, here is the reprex I have:

```r
handle <- sdf_len(sc, 1) %>%
  spark_apply(function(e) as.Date("2017-05-13"), columns = "dttm")

crassy::spark_write_cassandra_table(handle, "dst_bug", "tbl")

crassy::spark_load_cassandra_table(sc, "dst_bug", "tbl", "read_spk_tbl")
```

```
# Source:   table<read_spk_tbl> [?? x 1]
# Database: spark_connection
        dttm
      <date>
1 2017-05-13
```

Will close this one, but please, do reopen this or a new one if you still find issues while getting date/time date out of Cassandra.

Thank you!
