### ISSUE TITLE
sparklyr docker image is available for China user

### ISSUE THREAD

**Issue by harryprince** [rstudio/sparklyr#108]
here is my post on zhihu.
https://zhuanlan.zhihu.com/p/21574497

**Comment by javierluraschi** [comment]
@harryprince I understand this issue is being used to communicate there is a new sparklyr docker image. While this is great news and I'll encourage users that ask for a docker image to check this out, I believe submitting a blog post would be more helpful to the community.

Please feel free to reopen this issue if I misunderstood. Cheers.
