### ISSUE TITLE
DBI interface needs to implement sqlParseVariables generic

### ISSUE THREAD

**Issue by jjallaire** [rstudio/sparklyr#110]
In order to work with knitr sql chunks we need to implement the `sqlParseVariables` generic. This example illustrates the problem:

``````
```{r}
library(sparklyr)
library(dplyr)
sc <- spark_connect(master = "local", version = "2.0.0-preview")
iris_tbl <- copy_to(sc, iris, overwrite = TRUE)
```

```{sql, connection=sc}
SELECT * FROM iris
```
``````

@hadley Do you know whether there is a default implementation of this we can delegate to?

**Comment by hadley** [comment]
The default is just:

```R
setMethod("sqlParseVariables", "DBIConnection", function(con, sql, ...) {
  sqlParseVariablesImpl(sql,
    list(
      sqlQuoteSpec('"', '"'),
      sqlQuoteSpec("'", "'")
    ),
    list(
      sqlCommentSpec("/*", "*/", TRUE),
      sqlCommentSpec("--", "\n", FALSE)
    )
  )
})
```

`sqlParseVariablesImpl()` is exported so you should be able to make your own spec pretty easily

(But I don't see the problem because I don't see any variables in that example?)

**Comment by jjallaire** [comment]
The method is always called so we'll hit the problem even with no variables:

https://github.com/yihui/knitr/blob/0652b6e05339c908ae07eae0abf268009bb96819/R/engine.R#L383-L391

**Comment by kevinushey** [comment]
I can take a look at this.

**Comment by kevinushey** [comment]
Implemented here:

https://github.com/rstudio/sparklyr/commit/677f43929b26cab409212a6655af2956b12f80cb

However, this feels kind of brittle since we now have the `spark_connection` class 'pretending' that it is a `DBIConnection` for this specific context, whereas normally we have two separate objects (the `spark_connection` and `DBISparkConnection` classes / objects are separate things right now, for better or worse)

**Comment by jjallaire** [comment]
Thanks!

Yes, when Javier got the spark_connection object to also implement the DBI interface we had some S3 issues we couldn't sort out so some re-implementation of methods was necessary. I don't know that we've actually reached the right end state, just that things "work". For example, in theory we should be able to use the default dbGetQuery (and sqlParseVariables for that matter) implementation from DBIConnection however we had to do this:

https://github.com/rstudio/sparklyr/blob/122df963c853b479c6fdcdc5543cab192d2c7eff/R/dbi_spark_result.R#L51-L69

@javierluraschi Will remember better what broke when we didn't do this.

There's one other issue I just noticed that I'll make a separate comment about.

**Comment by javierluraschi** [comment]
@kevinushey yeah, regarding having a duplicate definition of `setMethod("dbGetQuery"..`, the problem was that `spark_connection` is an S3 object that we are using as a DBI connection. However, DBI requires S4 objects. There is a way to make S3 and S4 objects compatible using `setOldClass` which we are using. However, this is not sufficient since the DBI object is expected to derive from a `DBIConnection` class, which the S3 object implements but was not enough to make the S4 object aware of this relationship and this `dbGetQuery` was not being derived from the standard DBI implementation.

**Comment by hadley** [comment]
Did you try adding DBIConnection to the S3 class and the setOldClass call?

**Comment by kevinushey** [comment]
It sounds like this:

    methods::setOldClass("spark_connection")

might need to be

    methods::setOldClass(c("spark_connection", "DBIConnection"))

? If that works, we could potentially remove the need for the `DBISparkConnection`.

**Comment by javierluraschi** [comment]
@kevinushey tried the suggestion above, got this:

```
Error in methods::setOldClass(c("spark_connection", "DBIConnection")) : 
  inconsistent old-style class information for “DBIConnection”;
  the class is defined but does not extend “oldClass” and is not
  valid as the data part
```

**Comment by javierluraschi** [comment]
This works as expected today with Kevins fix.
