### ISSUE TITLE
ml_lda number of topics = columns of dataset why?

### ISSUE THREAD

**Issue by jwijffels** [rstudio/sparklyr#112]
When I look at the code of ml_lda, the number of topics is set to the number of columns from the dataset. Why would you do that as K is the number of topics you want to estimate, not the number of columns in the dataset.

```
model <- lda %>% invoke("setK", length(features)) %>% invoke("setFeaturesCol", 
        envir$features)
```

Wouldn't it make a lot more sense to provide the following types of arguments to ml_lda and use the setters accordingly?
- k = 5: number of topics
- optimizer = c("online", "em")
- alpha = docConcentration: Concentration parameter for the prior placed on documents' distributions over topics. If not missing, use setDocConcentration.
- beta = topicConcentration: for the prior placed on topics' distributions over terms. If not missing, use setTopicConcentration.
- maxIter = 100, 
- seed = 123456789
- subsamplingRate = 0.05

**Comment by kevinushey** [comment]
This was a silly oversight -- I'll expose `k` as a parameter in `ml_lda`.

**Comment by kevinushey** [comment]
I'll look into exposing the other parameters soon as well.

**Comment by dselivanov** [comment]
@jwijffels, this is off topic, but... From my experience, spark LDA implementation is totally disappointing... 
Last time I tried it (spark 1.6),  it even didn't work on medium datasets which can be fitted on single core with R `lda` package...

**Comment by jwijffels** [comment]
I would love to hear your experiences on this.
I'm evaluating currently 
- the (parallel) spark LDA alongside 
- the single core topicmodels R package and 
- the parallel LDA from Madlib on a Greenplum environment
- streaming topic models available at https://github.com/intel-analytics/TopicModeling
regarding speed, RAM, goodness of fit and size of the dataset, the type of algorithm (Expectation/Maximisation or Gibbs)
My term/document matrices datasets range mostly about 1-5 Mio rows about 1000 terms depending on what I choose.
If you  have experiences to share, feel free.

**Comment by dselivanov** [comment]
* Spark LDA requires a lot of spark internals tuning. And it is hard to understand why it can crash/goes OOM/goes full gc. I even tried to parse java garbage collector logs... With a lot of tuning I managed it to work with collection of 1M docs and 100 topics (on a cluster with 64 cores and 128 gb of ram!).
* I didn't try Madlib and intel-analytics/TopicModeling.

IMHO your datasets are not so large. I would go with single machine implementations of LDA. For example:

* [Mallet](http://mallet.cs.umass.edu/) which implements SparseLda algorithm.
* [VowpalVabbit](https://github.com/JohnLangford/vowpal_wabbit) with fast online variational bayes.
* [gensim](https://github.com/RaRe-Technologies/gensim)
* [Single Machine implementation of LDA from DMLC repo](https://github.com/dmlc/experimental-lda)

Regarding R packages:

* `topicmodels` is slow and unclear. `lda` is faster(~5x) and has more options. `LDA` in my [text2vec](https://github.com/dselivanov/text2vec) package is based on `lda`, but code is refactored - it ~1.5x-2x faster than `lda` (so ~10x faster than topicmodels). For 1000 topics, each iteration of collapsed gibbs sampling on 1.5m wikipedia subset (1/3 of english wikipedia) takes about 40 minutes. I guess algorithm needs 50-100 iterations to converge. Complexity is proportional to number of topics.  Also `text2vec::LDA` allows to fit model on subset of data and predict topic distribution for whole dataset.
* [R wrapper for Mallet](https://github.com/mimno/RMallet)
* I don't know any online implementations in R. I developed one, based on scikit-learn/gensim, but it still buggy. So I didn't publish it.

**Comment by jwijffels** [comment]
Thanks for the feedback and the pointers to other options.
The single-core lda in the topicsmodels package I'm running takes from 5 minutes up to 1.5 days depending on the number of topics (5 to 80), that's a bit too long even though I reduced the dataset already from 200Mio documents to the customer level. I'll have a look if package lda is faster and gives the same perplexity. For the other (online or batch) topic models I enumerated, I'll make a blog post about my experiences where my preference is currently to keep the data & the model in the DB if that DB allows sparse formats and to allow parallelism as much as possible (if this gives performance gains of course).

**Comment by javierluraschi** [comment]
Model updated by Kevin, closing issue.

**Comment by javierluraschi** [comment]
@jwijffels did you end up writing a blog post? would love to hear feedback from running `lda` at scale from `sparklyr`.

**Comment by jwijffels** [comment]
not yet, i'm still discussing on if I can use certain (currently confidential) data in the blog post.

**Comment by iamkbpark** [comment]
I will also look forward to hearing any example on lda from sparklyr!

**Comment by javierluraschi** [comment]
Here is an example:

```
devtools::install_github("rstudio/sparklyr", ref = "feature/ft_count_vectorizer")

library(janeaustenr)
library(sparklyr)
library(dplyr)

sc <- spark_connect(master = "local")

austen_books <- austen_books()
books_tbl <- sdf_copy_to(sc, austen_books, overwrite = TRUE)
first_tbl <- books_tbl %>% filter(nchar(text) > 0) %>% head(2)

first_tbl %>%
  ft_tokenizer("text", "tokens") %>%
  ft_count_vectorizer("tokens", "features") %>%
  ml_lda("features", k = 4)
```

**Comment by iamkbpark** [comment]
I do appreciate the straight forward example!

**Comment by iamkbpark** [comment]
Dear Team:

Based on the clear example of `ml_lda()`, now I can successfully fit the model with my data. Compared to the fitting speed of `LDA()` from `topicmodels` package in my single PC, it is such an amazing experience as a novice user of `Spark` & `SparklyR`. I do appreciate that. 

Since I am `R`-myopic user and have only got accustomed to use `LDA()` from `topicmodels`, several questions still remain unanswered though Spark Documentation seems well explained.
Some of the questions are as follows:

1. It seems there are two notable output objects after fitting `ml_lda()`: **`topic.matrix`** & **`estimated.doc.concentration`**

- **`topic.matrix`**: my main question is, "**How could I interpret the value of this table?**" or **"What values are these?"**
Spark Document says (https://spark.apache.org/docs/1.4.0/api/java/org/apache/spark/mllib/clustering/LDAModel.html#vocabSize()), it is a `VocabSize` & `K`, but I still don't understand what the cell value means and how I can interpret those. 

- **`estimated.doc.concentration`**: Also, please advise how to interpret these values. (Are these Alpha?)

2. **How could I access or examine the actual words of`VocabSize`?**  What I would like to explore is the fundamental output in `LDA()` such as **Top-Terms in each Topic**(ex. get_terms(), terms(), topics() functions in topicmodles package)

3. Lastly, How could I access the outputs similar to LDA() such as Beta, Gamma, Log-Likelihood(to find Optimal K)?

I am a bit confused about parameters used in ml_lda() since I am a newbie and if you could advise aforementioned questions, it will be greatly appreciated.
Thank you so much for your effort, time and help.

Sincerely,
K.B. Park
