### ISSUE TITLE
Sparklry installation failed on centos

### ISSUE THREAD

**Issue by junsbabay** [rstudio/sparklyr#117]
The server where I deployed Rstudio is closer to the spark cluster.
When I executing the command "devtools::install_github("rstudio/sparklyr")",  it returns the following 
infomation :
_Downloading GitHub repo rstudio/sparklyr@master
from URL https://api.github.com/repos/rstudio/sparklyr/zipball/master
Error in curl::curl_fetch_memory(url, handle = handle) : 
  Couldn't connect to server_

I'v tried using proxy, but it doesn't work. 
library(httr)
set_config(use_proxy(url="127.0.0.1", port=1080, username="",password=""))

Here is more infomation about my software version.
linux Centos 6.4
R 3.2.3
Rstudio Server 0.99.1261

**Comment by javierluraschi** [comment]
sparkly r uses `download.file` which would require to set the proxy with an environment variable, for instance:

```
Sys.setenv(http_proxy = "http://127.0.0.1:1080")
```

To properly configure proxies see: https://support.rstudio.com/hc/en-us/articles/200488488-Configuring-R-to-Use-an-HTTP-or-HTTPS-Proxy

**Comment by junsbabay** [comment]
Thank you for your great help , I 'v installed sparklyr successfully by using proxy.

**Comment by javierluraschi** [comment]
@junsbabay yes, you could use the "clone or download" button to download sparklyr as zip from the github page: https://github.com/rstudio/sparklyr

Or download directly from here: https://github.com/rstudio/sparklyr/archive/master.zip

BTW. I believe my original answer was not correct since this was an installation issue with `devtools::install_github`, I assumed the problem was in `spark_install` command to which you might still need to set the `http_proxy` environment appropiately.

Closing since this issue looks resolved to me.

**Comment by junsbabay** [comment]
@javierluraschi  You are right, the issue was about the devtools::install_github,  but the solution is to set a proxy to download the package.  

I tried to download the https://github.com/rstudio/sparklyr/archive/master.zip , and installed the master.zip by using devtools::install_local , however, it still tried to download some packages that required the proxy. LOL. 

BTW, I'v also installed spark and intended to use the sparklyr in cluster mode. Thanks a lot.

**Comment by javierluraschi** [comment]
@jimhester is there a recommended way to set proxies for `devtools`? @junsbabay is getting download errors while trying to install `sparklyr` from github. Any thoughts would be much appreciated, thanks!

**Comment by jimhester** [comment]
You could try using `install_url("https://github.com/rstudio/sparklyr/archive/master.zip", config = use_proxy(url="127.0.0.1", port=1080, username="",password=""))`, passing the proxy directly to the config parameter.

Otherwise setting the proxy both ways as mentioned above is probably the best option.

**Comment by junsbabay** [comment]
@jimhester @javierluraschi  Thank you for helping me with the installation problem.
I'm sorry,I didn't make myself clearly.  With the proxy, I'v installed sparklyr successfully.
However, if downloading directly from https://github.com/rstudio/sparklyr/archive/master.zip without proxy, you'll need some packages that required proxy when installing  the zip by the function of devtools::install_local.

I think the issue has been resolved. I'm appreciating for your help and the fabulous package!
