### ISSUE TITLE
Consider using default formula in all ml functions

### ISSUE THREAD

**Issue by javierluraschi** [rstudio/sparklyr#1261]
Works on `sparklyr 0.6.4`...

```
library(sparklyr)
library(ggplot2)
library(dplyr)

sc <- spark_connect(master = "local")
iris_tbl <- copy_to(sc, iris, "iris", overwrite = TRUE)

iris_tbl %>%
  select(Petal_Width, Petal_Length) %>%
  ml_kmeans(centers = 3)
```

Not in `sparklyr 0.7.0`, would require:

```
iris_tbl %>%
  select(Petal_Width, Petal_Length) %>%
  ml_kmeans(centers = 3, ~ .)
```

**Comment by kevinykuo** [comment]
This is a necessary breaking change.

`ml_kmeans.tbl_spark()` does one of two things: 
- If `formula` is not specified, it instantiates a `KMeans` estimator and immediately fits the estimator with the data, returning a `KMeansModel`. In this case it looks to the `features_col` argument for the vector column it should cluster on. 
- If `formula` is specified, it creates a `Pipeline` where the first stage is an `RFormula` to pre-process the data, and the second stage is `KMeans`. It then fits the `Pipeline` and returns a wrapper of the `PipelineModel`.

So something like this would work:
```
iris_tbl %>%
  ft_vector_assembler(c("Petal_Width", "Petal_Length"), "features") %>%
  ml_kmeans(k = 3)
```
or this
```
iris_tbl %>%
  ft_r_formula(~ Petal_Width + Petal_Length) %>%
  ml_kmeans(k = 3)
```
Note that this issue only affects unsupervised (e.g. clustering) algorithms, and really only `ml_kmeans()` in 0.6, since for classification/regression there's no way to guess what the response ought to be. We can probably do better in terms of error messages in some cases, e.g. we can check for existence of columns on the R side rather than printing a Java stack trace.
