### ISSUE TITLE
more efficient csv_string serialization

### ISSUE THREAD

**Issue by lawremi** [rstudio/sparklyr#1464]
Was just glancing at the code and saw that serialization to a string of CSV writes to a temporary file. It would probably be more efficient to avoid the disk using the newly optimized `textConnection()`. Especially if storage is remote.

**Comment by kevinykuo** [comment]
Turns out it's faster to write to and read from CSV on disk, because the respective writers/readers are optimized. It's more expensive to mess with converting from column representation to row representation. The ideal solution to all our `copy_to()/collect()` issues is https://github.com/rstudio/sparklyr/issues/1457.

**Comment by lawremi** [comment]
Well, `write.table()` is not going to be any slower going into a memory buffer. Not sure about  `readr::read_lines()` vs just `readLines()`. I did make `readLines()` roughly a couple times faster last release cycle by using buffering. But judging the performance of file vs. memory is complicated, as file systems can be remotely mounted, disks can vary in speed, etc. There are other complications with touching the disk.

I agree Arrow serialization is the way to go in the long run. This is a simple, short-term tweak.
