### ISSUE TITLE
Async support

### ISSUE THREAD

**Issue by javierluraschi** [rstudio/sparklyr#1546]

**Comment by nathaneastwood** [comment]
@yitao-li any idea why this was opened and closed? It would be really nice to have,

**Comment by yitao-li** [comment]
@nathaneastwood This was closed because it was more or less identical to https://github.com/sparklyr/sparklyr/issues/2116

https://github.com/sparklyr/sparklyr/issues/2116 is currently a wish-list item because it would be nice to have, but at the moment it is unclear how to avoid issues with `future` or other similar async R package trying to serialize Spark connection objects. It would be nice if `future` has something simliar to `@transient` in Java for marking some R objects as inherently non-serializable.

**Comment by nathaneastwood** [comment]
Ah interesting. Thanks a lot.
