### ISSUE TITLE
Spark version upgrade breaks install

### ISSUE THREAD

**Issue by davejshirley** [rstudio/sparklyr#1645]
Version 2.3.0 has been removed from the Apache server at https://www-us.apache.org/dist/spark/
It has been replaced by version 2.3.1 (not supplemented).  The code and jsons in sparklyr have not been updated.

My temporary solution was to replace all 2.3.0 instances in code and jsons with 2.3.1, and prevent the "latest" json being fetched from `spark_versions_url()`

**Comment by javierluraschi** [comment]
@davejshirley this was fixed with https://github.com/rstudio/sparklyr/commit/09638025f0c1dddf1d7f85aaa1af78684150ea0d#diff-c01e52fd96a99c697c5838596269d4a5

The way `spark_install()` works is as follows...

If there is internet connectivity, it will check for the latest version of this file once per session and download the updated values.

If there is no internet connectivity, it will use the copy included in the `sparklyr` package.

My guess is that you are in a no-connectivity scenario or something is blocking this? Otherwise, you shouldn't be hitting this issue. There could also be a proxy caching this file... https://raw.githubusercontent.com/rstudio/spark-install/master/common/versions.json, is this the case perhaps?

**Comment by davejshirley** [comment]
@javierluraschi  Thanks for the prompt reply.  Upon complete clean reinstall the stock package works as intended; I am now unable to reproduce my problem, so I am guessing it was some kind of caching / connectivity issue that was temporary.

Sorry to have wasted your time!

**Comment by davejshirley** [comment]
(also this is a partial duplicate of issue [#1602](https://github.com/rstudio/sparklyr/issues/1602) )
