### ISSUE TITLE
Additional parallel processing for rows within spark_apply()

### ISSUE THREAD

**Issue by jyk** [rstudio/sparklyr#1699]
I have general question. Does it make sense to use additional parallelization within spark_apply() or does spark_apply() take care of parallelization of chunk of Spark Data Frame by itself ?
For instance does it make sense to use foreach package within function provided to spark_apply()  ?
I did not found any explanation of that issue in RStudio's webinars etc

**Comment by javierluraschi** [comment]
`spark_apply()` makes use of Spark to distribute computation; however, assuming that your cluster is fully utilized with `sparklyr` (say, if you have 3 worker machines nodes with 8 cores each, if you have correctly configured 24 executors) and that data is partitioned to fully utilized your cluster (say, by using `sdf_repartition(sc, 24)`) then no, it doesn't make sense to use additional parallelization with `spark_apply()` since Spark is already taking as much advantage of the resources as possible.

However, suppose there is an R package that does use multiple cores (say to run a simulation or why not). In this case, it would make sense to use the additional parallelization that the R package provides (say, using 8 cores per executor, you can use the `sparklyr.shell.executor-cores` configuration setting which sets `--executor-cores` in `spark-submit`) and then repartitioning only over as many machines, not cores (say by repartitioning the data with `sdf_repartition(sc, 3)`).

That said, I think the short answer is in general **NO**, we don't need to use additional parallelization with `sparkl_apply()`.

**Comment by jyk** [comment]
Big thanks to quick answer!
