### ISSUE TITLE
left_join doesn't work

### ISSUE THREAD

**Issue by AITikhonov** [rstudio/sparklyr#182]
I have 2 tables, in every 3 identical a column name (they are a connection key). 
But in attempt to make left join I receive a error - "this functionality isn't maintained in Spark 1.6. Try to use Spark 2.0 or avoid identical names" (text approximately).

Spark 1.6.1.

How to execute an left_join?
Thanks.

**Comment by kevinushey** [comment]
Can you please provide your code + a reproducible example?

**Comment by javierluraschi** [comment]
@AITikhonov we are aware of this issue and have provided a fix for dplyr to be compatible with Spark. The PR is here: https://github.com/hadley/dplyr/pull/1997 so one workaround is to build dplyr from source using that PR, or alternatevely, this issue is not present in Spark 2.0.0 since it added additional Spark SQL syntax that is compatible with the current version of dplyr.

**Comment by AITikhonov** [comment]
Thanks.
Temprorary I use rename function dplyr for rename column. It's work.
