### ISSUE TITLE
broom::tidy(logistic_regression) doesn't return most statistics

### ISSUE THREAD

**Issue by ormachea** [rstudio/sparklyr#1841]
When I run broom::tidy on logistic regression output, it only returns coefficients and no other statistics.  Any way to help?  This is a very cool package but without the extra functionality, I won't be able to rely on the functions.  Thanks!

```r
spark_version <- "2.0.0"
sc <- spark_connect(master = "local", version = spark_version)

# your reproducible example here
```

model <- mtcars_tbl %>% ml_logistic_regression(mpg ~ cyl + disp)
broom::tidy(model)

**Comment by kevinykuo** [comment]
I don't think there's much we can do here since the statistics aren't provided by Spark (https://spark.apache.org/docs/latest/api/scala/index.html#org.apache.spark.ml.classification.LogisticRegressionSummary). You can consider filing an issue upstream https://issues.apache.org/jira/projects/SPARK/issues/SPARK-26709?filter=allopenissues.
