### ISSUE TITLE
Problem with ft_one_hot_encoder

### ISSUE THREAD

**Issue by Scotturbina** [rstudio/sparklyr#1995]
Hello, I am having problems with ft_one_hot_encoder function,

This is what I am doing (test_query comes from sdf_sql function)

```
test_query<-test_query %>% 

mutate(CORP_IN=ifelse(is.na(CORP_IN),"MISSING",CORP_IN ))%>%
mutate(CORP_IN_enc=ft_one_hot_encoder(CORP_IN))

```

And I receive an error:

```
Error: org.apache.spark.sql.AnalysisException: Undefined function: 'FT_ONE_HOT_ENCODER'. This function is neither a registered temporary function nor a permanent function registered in the database 
```

---

```r
spark_version <- "2.3"
sc <- spark_connect(master = "yarn", version = spark_version)

**Comment by benmwhite** [comment]
The `ft_*` functions should be used on their own and not inside dplyr verb calls. They take Spark tables as inputs.

**Comment by Scotturbina** [comment]
@benmwhite so it can take the output of a sdf_sql function as input right? Do you have some example?

**Comment by benmwhite** [comment]
Look through posts with ML pipeline examples for that. I'm pretty sure there are some official sparklyr and RStudio blog posts that go through it. It basically works the same way as piping Spark tables through them except you're specifying a pipeline step instead of immediately performing the transformation on data.

**Comment by Scotturbina** [comment]
Thank you, that's work for me
