### ISSUE TITLE
Problem with ML pipelines

### ISSUE THREAD

**Issue by Scotturbina** [rstudio/sparklyr#2015]
Hello,

I am trying to predict an SQL statement with a pipeline.

I am using in the pipeline the column that needs to be predicted in order to adjust and evaluate the model before saving it and loading it into a new session.
When I use the model in order to predict new data is asking me the predicted column.

Here it is my spark config:

```
config <- spark_config()
config$spark.executor.cores <- 4
config$spark.executor.memory <- "8G"
config$spark.executor.instances <- 4
config$spark.driver.memory="10G"
config$spark.rpc.message.maxSize <- 1024


config$spark.yarn.queue<- "root.bis.cis_us_edfbissvcs"

spark <- spark_connect(master = "yarn-client",version = "2.3.0",app_name = "Test",
                   config=config)
```

Here it is my pipeline ( IS_Commercial is my column to predict):

```
NameDropperPipe<-ml_pipeline(spark) %>%

ft_dplyr_transformer(
    tbl = test_query2
    )%>%
    ft_string_indexer(
    input_col="IS_Commercial",
    output_col="IS_Commercial_idx"
    )%>%
    ft_r_formula(IS_Commercial_idx~.,
    )%>%
    ml_random_forest_classifier(impurity ="gini",max_depth = 20, num_trees = 2500,
   feature_subset_strategy = "15")

  

partitioned_Name_D <- sdf_partition(
  test_query,
  training = 0.8,
  testing = 0.2
)


fitted_Name_D_pipeline<- ml_fit(
  NameDropperPipe,
  partitioned_Name_D$training
) 

```

Here I save my pipeline

```
ml_save(
  fitted_Name_D_pipeline,
  "NameDropper_model",
  overwrite = TRUE
)
```

Here I load My new pipeline I try to predict new data

```

RF_model <- ml_load(spark, "NameDropper_model")

predictions <- ml_transform(
  RF_model,
  test_query2
)

```

However I am having this error:

```
Error: java.lang.IllegalArgumentException: Field "IS_Commercial" does not exist
```

Does somebody know why I need IS_Commercial to predict values?

**Comment by benmwhite** [comment]
From [the documentation](https://cran.r-project.org/web/packages/sparklyr/sparklyr.pdf) for `ft_dplyr_transformer()`:  "Internally, the `ft_dplyr_transformer()`extracts the dplyr transformations used to generate `tbl` as a SQL statement then passes it on to `ft_sql_transformer()`." 

And for `ft_sql_transformer()`: "Implements the transformations which are defined by SQL statement."

So this function will take all the dplyr steps used to create `tbl`, translate it to Spark SQL, and apply those transformations to whatever comes through the pipeline. I have no idea what your `test_query2` is, but if you used it to create the dplyr stage and then try to run it through the entire pipeline again, your pipeline is going to try to reapply the transformations used to create `test_query2` to `test_query2` itself.

This is all guesswork without a reprex, but your error message is probably from the string indexing stage not finding the "IS_Commercial" column from the initial transformation stage.

Instead of inputting `test_query2` in your saved pipeline, try using the original table used to create `test_query2`, or alternatively remove the dplyr stage and create a new pipeline starting with the string indexing stage if you want to use `test_query2` as the input.

**Comment by Scotturbina** [comment]
Hello @benmwhite  I was finally able to get it done by using the dplyr transformer outside the pipeline.

Then I got 2 saved models, one for data processing and other that contains the model and everything is running very good!

Thanks a lot for your help
