### ISSUE TITLE
Implement function quantile

### ISSUE THREAD

**Issue by Tarqui** [rstudio/sparklyr#204]
I wonder if it could be possible to implement the quantile function

**Comment by slopp** [comment]
You can do this use dplyr's ntile function - note that Sparklyr's dplyr backend supports window functions:

```{r}
library(dplyr)
rnorm_tbl <- copy_to(sc, list(x=rnorm(1001)), "rnorm")
query <- rnorm_tbl %>% 
  mutate(q = ntile(x,4))

# to see the Spark SQL translation
sql_render(query)

# to execute and bring results back to R
result <- query %>% collect()

plot(q~x, data=result)
summary(result)
```

**Comment by kevinushey** [comment]
Is it worth considering implementing both `quantile` and `ntile` here?

**Comment by slopp** [comment]
Personally I don't think so, but it probably worth expanding the window function section of the dplyr doc ... or at least linking to the dplyr vignette. I think once you find the ntile function its straightforward to get quantiles.

**Comment by magarick** [comment]
@kevinushey @slopp I think it is worth it. They have different use cases and you can't directly get quantiles from ntile without some inefficient gymnastics. For instance, right now I'm working on something where what I care about is the median and two other quantiles to get a sense of the range of the data. Doing this with ntile would be painful. ntile also only allows uniformly sized buckets which isn't always ideal.

I know that spark itself has some approximate quantile functions built in but these do not appear to be exposed here. I guess exact quantiles can become a problem with large amounts of data? Anyway, hope this commentary is useful and I'm happy to help on this since I think it's pretty important.

**Comment by slopp** [comment]
@magarick that commentary is helpful. 

@kevinushey we should be able to implement all of these: https://spark.apache.org/docs/latest/api/scala/index.html#org.apache.spark.sql.DataFrameStatFunctions 

Though I am not sure what the best interface would be, given dplyr doesn't really have these functions...

**Comment by kevinushey** [comment]
I've added `sdf_quantile()` as an interface to this function for now; we can think about extending this in the future.

**Comment by raphael-psr** [comment]
Hey guys, does anyone know if there is any way to do something like this:

group_by(stage) %>% summarize(quantile = quantile(c1, 0.95))

I can do it using dplyr locally but not as a spark query.

**Comment by dalloliogm** [comment]
I have the same problem as @raphael-psr , I can calculate the quantile on the whole data frame, but not on a grouped column.

**Comment by jmerone** [comment]
@kevinushey Has there been any update to finding the median of a grouped sparklyr dataframe? The suggestion by @dalloliogm computes an approximate median. Is there a way to to perhaps register the `stats::median` function or `stats::quantile` function as a udf?

**Comment by kevinushey** [comment]
I haven't been involved with `sparklyr` development for a little while but my understanding is that the cleanest way forward right now would be to use `spark_apply()` alongside any R functions you need to run.

**Comment by kevinykuo** [comment]
@jmerone I think there's a spark sql function for this, look up quantile approx or something to that effect.
