### ISSUE TITLE
Logging into spark log from R Script

### ISSUE THREAD

**Issue by uday1889** [rstudio/sparklyr#2101]
Here's my question. Using python I would log the output of a python script with pyspark into spark log as below:

```
log4jLogger = sc._jvm.org.apache.log4j
LOGGER = log4jLogger.LogManager.getLogger(__name__)
LOGGER.info("pyspark script logger initialized")
```

Is something like this possible with sparklyr?

The idea is then to call  ```sparklyr::spark_log``` to retrieve spark and application log (in a distributed setup) from executors cluster wide.

**Comment by dbast** [comment]
Are you maybe looking for `sparklyr::spark_apply_log()`?

**Comment by javierluraschi** [comment]
`sparklyr::spark_log()` does not return the distributed logs, just the driver logs. So you would have to use whatever your cluster manager provide to return those logs, say in the YARN or Mesos UI.

If you need to log from R (instead of Python), then as dbast mentions, you can use `spark_apply_log()`.

**Comment by uday1889** [comment]
Thanks for your comment and all the great work @javierluraschi 
Found some details I was looking for in your answer here: 
https://stackoverflow.com/questions/46396736/sparklyrs-spark-apply-function-seems-to-run-on-single-executor-and-fails-on-mod
