### ISSUE TITLE
sdf_with_sequential_id index is not integer?

### ISSUE THREAD

**Issue by kohleth** [rstudio/sparklyr#2106]
---
Hi team,

`sparklyr::sdf_with_sequential_id` produces indices that is of type `double` instead of `integer`, even if we specify `from=1L`. Is this expected, given indices are usually integer?

```r
sdf_iris=sdf_copy_to(sc,iris,'iris')
sdf_iris%>%sdf_with_sequential_id(id='iris_id')
sdf_iris%>%sdf_with_sequential_id(id='iris_id',from=1L)
sdf_iris%>%sdf_with_sequential_id(id='iris_id',from=1L)%>%mutate(iris_id=as.integer(iris_id))
```

**Comment by benmwhite** [comment]
Under the hood the sparklyr function `sdf_with_sequential_id()` uses the Spark Java API's `zipWithIndex()` method [which returns floats rather than integers](https://spark.apache.org/docs/2.4.3/api/java/org/apache/spark/rdd/RDD.html#zipWithIndex--). So it looks like the behavior is at least intended even if it's not necessarily expected.
