### ISSUE TITLE
Sparklyr to Spark ML - Integration & Architecture

### ISSUE THREAD

**Issue by ganeshmailbox** [rstudio/sparklyr#234]
Hi Team,

I would like to thank you all for bringing about a pretty nifty open source tool for R users. I have few request for clarifications:

1. I see currently sparklyr is integrated with Apache Spark API, i am assuming you are using spark.mllib package for running the machine learning algorithm internally. Is that correct understanding?
2. As you know spark is moving from RDD to more DataFrame based approach, though RDD is still supported, in doing so they are moving to spark.ml libraries. Are there any plans for sparklyr to use the new dataframe API (spark.ml packages) as and when it becomes available? 
3. I got to know that sparklyr is using sparkr internally ([SPARK-16326](https://issues.apache.org/jira/browse/SPARK-16326)), can you comment on the same?  

Once again, thanks for great tool !

Ganesh

**Comment by jjallaire** [comment]
We are actually using the new data frame based `spark.ml` APIs rather than the legacy `spark.mllib` APIs (note that Apache Spark documentation still refers to both under the moniker of "MLlib" which is a bit confusing.

We don't actually call SparkR directly. That said, our R to Java binding is indeed based on the original SparkR implementation, but we've made some changes to improve performance and (soon) to improve interoperability with yarn clusters and RPC based access to remote Spark clusters.

**Comment by ganeshmailbox** [comment]
Great ! this helps.
