### ISSUE TITLE
Consider adding support for Word2Vec and TF-IDF

### ISSUE THREAD

**Issue by javierluraschi** [rstudio/sparklyr#247]

**Comment by aissaelouafi** [comment]
I agree, It will be very useful for text minning and NLP needs. I think we can get the same result using dplyr library.

**Comment by good-marketing** [comment]
I tried to create an extension for the coreNLP Spark package, which supports various nlp functions, but as a newbie I am stuck, perhaps you can Have a look at http://stackoverflow.com/questions/40064818, thanks!

**Comment by p2004r** [comment]
`sdf_mutate(ft_tokenizer())` return <list><list [xx]> (xx match count off words in input string)

Consequently `sdf_mutate(ft_hashing_tf())` return:

> ensure_scalar_boolean(binary) :
>   '"ft_hashing_tf(input.col = \"V8\", outpu..."' is not a length-one logical vector

`sdf_mutate(ft_hashing_tf(n.features=100))` return <list><dbl [100]>

I added a the function ft_hashing_tf()  from the commentaries

` ft_hashing_tf <- function(x,
                           input.col = NULL,
                           output.col = NULL,
                           n.features = NULL,
                           binary = FALSE,
                           ...)
 {
   sparklyr:::ml_backwards_compatibility_api()
   class <- "org.apache.spark.ml.feature.HashingTF"
   sparklyr:::invoke_simple_transformer(x, class, list(
     setInputCol    = ensure_scalar_character(input.col),
     setOutputCol   = ensure_scalar_character(output.col),
     setNumFeatures = ensure_scalar_integer(n.features),
     setBinary      = ensure_scalar_boolean(binary)
   ))
 }
`

The problem is the type returned from ft_hashing_tf()?

Maybe similar case is [deserialize DenseVector as arrays #326](https://github.com/rstudio/sparklyr/pull/326) ?

**Comment by kevinykuo** [comment]
@good-marketing have you made any progress since last year? Also interested in a corenlp wrapper.

**Comment by good-marketing** [comment]
@kevinykuo No sorry, but I'll try to pick it up over the next weeks. I'll keep you informed if I do make some progress.

**Comment by kevinykuo** [comment]
Tracking in https://github.com/rstudio/sparklyr/issues/1092
