### ISSUE TITLE
fix imports to avoid namespace collision

### ISSUE THREAD

**Issue by jangorecki** [rstudio/sparklyr#272]
Installing recent head I'm getting following warnings:
```sh
R CMD INSTALL sparklyr_0.4.16.tar.gz 
#* installing to library ‘/home/jan/R/x86_64-pc-linux-gnu-library/3.2’
#* installing *source* package ‘sparklyr’ ...
#** R
#** inst
#** preparing package for lazy loading
#Warning: replacing previous import by ‘dplyr::copy_to’ when loading ‘sparklyr’
#Warning: replacing previous import by ‘magrittr::%>%’ when loading ‘sparklyr’
#Warning: replacing previous import by ‘tibble::data_frame’ when loading ‘sparklyr’
#** help
#*** installing help indices
#** building package indices
#** testing if installed package can be loaded
#Warning: replacing previous import by ‘dplyr::copy_to’ when loading ‘sparklyr’
#Warning: replacing previous import by ‘magrittr::%>%’ when loading ‘sparklyr’
#Warning: replacing previous import by ‘tibble::data_frame’ when loading ‘sparklyr’
#* DONE (sparklyr)
```
@kevinushey R 3.2.1

**Comment by kevinushey** [comment]
What version of R are you using? I don't see these warnings with R 3.3.1 patched.

**Comment by kevinushey** [comment]
Evidently the issue is caused by mixing `import` and `importFrom` declarations in a `NAMESPACE` file in older versions of R: http://stackoverflow.com/questions/8662285/warning-replacing-previous-import-head-when-loading-utils-in-r

Not sure if it's worth fixing in `sparklyr` since the underlying issue in R has already been resolved. (I repro'ed in R 3.1.3 but not in R 3.2.5)

**Comment by jangorecki** [comment]
@kevinushey see https://github.com/jangorecki/sparklyr/commit/b966bdd7d4388563fd140f97783d552c7d44936b it fixed those warning and also pass `R CMD check`

**Comment by kevinushey** [comment]
Ah, didn't realize it was going to be that easy. Thanks!
