### ISSUE TITLE
Connecting to EMR from a separate EC2 instance

### ISSUE THREAD

**Issue by kykuo** [rstudio/sparklyr#280]
EMR clusters on AWS don't persist through termination, so I've set up a EC2 instance that runs on EBS for my ad-hoc data science tasks. Now I'd like to spin up EMR clusters as needed and utilize them from a RStudio session on my single-node instance.

If I were to run RStudio on the cluster master node directly I'd pass `master = "yarn-client"` to `spark_connect`. But if I want to connect from the separate instance what should I set for `SPARK_HOME` and the parameters for `spark_connect`?

**Comment by javierluraschi** [comment]
@kykuo this is more of a question to AWS/EMR than to `sparklyr` but here are some thoughts.

I would first investigate how to connect from my local machine into EMR as `yarn-client`. This will probably involve setting an SSH connection and other networking considerations, but once you figure out a way to connect to EMR from outside EMR, transitioning this to `sparklyr` would be easier to accomplish.

That said, there are a couple caveats:
 1. In `yarn-client` mode, whoever initializes an Spark job, EC2 in this case, becomes the Spark driver node. It is usually the case that the driver node will contain more memory than the workers to support aggregation operations so having an small EC2 instance might not work in all cases.
 2. There is a significant amount of network traffic between the driver node (EC2) and the workers; therefore, this has the potential of becoming a performance bottleneck, might be less so since EC2 and EMR can be potentially located in the same data center, but still.

In general, we currently don't recommend using `sparklyr` outside of the Spark cluster, but we are investigating ways of enabling this in the future with other technologies.

**Comment by javierluraschi** [comment]
From `sparklyr 0.6` onwards, `yarn-cluster` mode is also supported and could be an alternative for this topology in EMR + EC2.
