### ISSUE TITLE
Behavior of NA

### ISSUE THREAD

**Issue by kykuo** [rstudio/sparklyr#293]
`NA_real_` is getting mapped to `NaN` -- is this expected behavior?

```
data <- data.frame(x = c(1.0, NaN, NA, 4.0), y = 1:4, stringsAsFactors = FALSE)
data_tbl <- copy_to(sc, data, overwrite = TRUE)

> data_tbl %>% collect
# A tibble: 4 × 2
      x     y
  <dbl> <int>
1     1     1
2   NaN     2
3   NaN     3
4     4     4
```

**Comment by kevinushey** [comment]
I believe this is expected behavior -- Spark doesn't really have the concept of `NA`s, only `NaN`s. 

Note that R's `NA`s are, under the hood, a 'special kind' of `NaN` value (as defined by the [IEEE 754](https://en.wikipedia.org/wiki/IEEE_floating_point) spec), and so are only really meaningful to R.
