### ISSUE TITLE
spark_read_csv - does it read the data into main memory of the R session?

### ISSUE THREAD

**Issue by codingbutstillalive** [rstudio/sparklyr#315]
Hi!

I try to load a big csv file into Spark with the spark_read_csv function of Sparklyr. The command takes very long to execute and it finally kills the RStudio session. When I look into the body of the function, I see the following line of code:

`df <- spark_csv_read(sc, spark_normalize_path(path), options)`

To me it looks like the data is actually fetched into the R-session! Why?

**Comment by codingbutstillalive** [comment]
Could you please provide a few more details. Why does it read the data into R?
The spark_read_csv function is incredibly  slow. 6 minutes compared 1 minute with read.df of SparkR.

**Comment by javierluraschi** [comment]
@codingbutstillalive with `spark_csv_read`, data is not loaded into R bur rather into the Java VM. In this case, when the Java process crashes, is also taking down the R session. I'll investigate this further to limit the crash to the `Java` process and try to avoid a crash in the `R` process.

Regarding your second question, there are a few differences between `sparklyr` and `SparkR`. One of them is the format we use to store memory in `Spark`.

While using `read.df` in `SparkR`, data is being loaded through `R` into memory maintaining a byte structure that is compatible only with `R`. `read.df` happens to be very efficient since it wraps a native code implementation, which in your case, loads this data in 1 minute.

In `sparklyr`, we use the standard `Scala` API functions to load data into memory and we maintain the byte structure provided by the JVM. The `Scala` implementation happens to be slower than the `R` implementation, `Scala` uses the `JVM` which is less performant in this case than `R` running a `C` implementation.

`sparklyr` makes use of the standard `Spark` data loading functions to be fully interoperable with other `Spark` functions and packages defined through the `Scala` API. This allows you to, once the data is loaded, run the ML algorithms available in Scala without the additional cost of transforming the internal byte representation which, at times, might not be feasible due to resource constrains. Because of this choice, `sparklyr` supports all MLlib algorithms and will be easier to have parity with Spark MLlib in the future.

Does this answer this question?

**Comment by codingbutstillalive** [comment]
Thanks for your explanations, and the affords! I really appreciate that.

It is kind of counter-intuitive that an R implementation can be more efficient than a scala one ;) 

Could you please explain to me the code line that I quoted. What is the nature of 'df' on the left side of the operator? It really looks as if the data were fetched and assigned to a data frame.

Today, I was trying to convince a Python-affine colleague from R's capabilities, especially with sparklyr and RStudio, but this terribly failed. First, it did not install under Windows - even with the beta preview of RStudio, then reading-in cvs data took that long, and finally we were missing intuitive functions like dim(), or an apply() function analogon. I am really sad that he couldn't be excited about R. I found that working with Spark data frames in SparkR - we gave it a little try - felt more intuitive, because it was straightforward to get the dimensions of the data table, or subsets of the data sets.

After all, to me it seems like I would currently need to use SparK and sparklyr in parallel,to be able to work completely. However, I understood from your explanations that this will not be possible due to different representations of the Spark data frames.

**Comment by javierluraschi** [comment]
@codingbutstillalive Regarding the `df <- spark_csv_read(sc, spark_normalize_path(path), options)` line:
 1. The code is invoking a command on Spark, as a rule of thumb, each time we use `sc` (the `SparkContext`) or the resulting object, it probably means we are executing something in the Spark cluster, not locally.
 2. `spark_normalize_path` is not using `sc` and therefore is a local call to make a local path spark-friendly.
 3. The `spark_csv_read` call triggers reading data directly in Spark and loads it into Spark.
 4. The resulting `df` object is an Spark `DataFrame`, similar to `SparkR` this not really an `R` data frame but a wrapper around a remote one. `SparkR` does provide utilities that mimic an `R` data frame like `dim()` and other well-known methods. In contrast, the default approach with `sparklyr` is to use `dplyr` instead. `dplyr` provides a clean grammar to manipulate data and is often easier to use than manipulating `df` directly. Therefore, to a `dplyr` user, `sparklyr` would feel very intuitive and I would personally encourage us to use `dplyr` to manipulate data frames. That said, `sparklyr` supports community development and encourages extensions so it would be possible for the `R` community to write a package to support `dim()` and other data frame functionality, you are very welcomed here to contribute in this space if this is of interest to you.

Do send any questions or comments our way, if you prefer, you can reach me out at javier at rstudion.com.

**Comment by codingbutstillalive** [comment]
Thanks a lot. I see your point with the dplyr style that supports intuition with the concept of the pipe operator. And I agree. But some basic functions like dim(), nrow(), ncol() should really be included in the sparklyr base package, in my opinion. This would help to promote the package.

Alright, I will contact you in case of further questions. It is a really nice offer of yours.

Best regards, Sebastian

**Comment by javierluraschi** [comment]
@codingbutstillalive thanks, we can consider this in here https://github.com/rstudio/sparklyr/issues/319 and close this one.

**Comment by javierluraschi** [comment]
Sounds good. Closing this one, ping me as a follow up if needed. Best, Javier
