### ISSUE TITLE
sqlInterpolate() and sqlParseVariables(): Change of interface

### ISSUE THREAD

**Issue by krlmlr** [rstudio/sparklyr#351]
The sparklyr package seems to be the only package that actually implements these generics. I'd like to get rid of the nonstandard argument names and use `conn, sql, ...` as interface (https://github.com/rstats-db/DBI/issues/147), and add an optional `.dots` or `.values` argument (https://github.com/rstats-db/DBI/issues/140#issuecomment-251189284).

Do you plan a CRAN release anytime soon, so that we can coordinate the changes needed in both packages?

**Comment by javierluraschi** [comment]
@krlmlr we are planning to push this to CRAN in about 2 weeks. If you want these changes before that, let me know to figure them out and push them in.

**Comment by krlmlr** [comment]
Thanks. I just released DBI 0.5-13 to GitHub, it contains the breaking changes (rstats-db/DBI#147). Could you make sparklyr work with both CRAN and GitHub versions?

**Comment by javierluraschi** [comment]
@krlmlr The CRAN version for sparklyr 0.4 is already released, so I won't be able to make a change to the current version and sparklyr would be broken for DBI 0.5-13 onwards. I could release a new version of sparklyr 0.5 that bumps the required version of DBI to 0.5.13 but not older ones since the signature changed. When are you planning to release DBI 0.5.13 to CRAN?

Could you shoot me an email to javier at rstudio? I'm buried in github notifications so it's going to be easier to coordinate this by mail. Thanks!

**Comment by javierluraschi** [comment]
From Kirill: "Please prepare for updating the signatures of sqlInterpolate() and sqlParseVariables(), DBI 0.6 will support both but DBI 0.7"

**Comment by javierluraschi** [comment]
Taking care of this in `0.5.3` patch release: https://github.com/rstudio/sparklyr/commits/bugfix/hotfix-0.5.3

**Comment by krlmlr** [comment]
You could add `DBI (>= 0.5-19)` to your `DESCRIPTION`.

**Comment by javierluraschi** [comment]
We took care of this in `sparklyr 0.5.3`.
