### ISSUE TITLE
sdf_save_table references non-existent function

### ISSUE THREAD

**Issue by kevinushey** [rstudio/sparklyr#391]
```
> sdf_save_table("foo")
Warning in sdf_save_table("foo") :
  sdf_save_table is deprecated, use spark_write_table instead.
Error: Unable to retreive a Spark DataFrame from object of class character
> spark_write_table
Error: object 'spark_write_table' not found
```

In addition, if `sdf_save_table()` is indeed deprecated, the `.Deprecated()` function should be used instead (rather than `warning()`).

**Comment by javierluraschi** [comment]
Thank you Kevin, `spark_save_table` and `spark_load_table` work in now Spark 2.0+. They were unfortunately broken since 0.4, which is interesting since I have not seen reports on this yet. My guess is that most users prefer to explicitly save with their desired format, say `spark_write_csv`, or `spark_write_parquet` rather than `spark_save_table` which calls `saveAsTable` and defaults to the format configured in Hive.
