### ISSUE TITLE
spark_normalize_path does not return anything on Windows

### ISSUE THREAD

**Issue by niklasvm** [rstudio/sparklyr#446]
With reference to issue #432. The function below does not return anything when the if statement evaluates to false.

```{r}
spark_normalize_path <- function(path) {
  # only normalize paths in OS that behave correctly for custom
  # protocols, in windows, this is not the case. See #432
  if (normalizePath("s3n://", mustWork = FALSE) == "s3n://") {
    normalizePath(path, mustWork = FALSE)
  }
}
```

I propose something of the form:

```{r}
spark_normalize_path <- function(path) {
  # only normalize paths in OS that behave correctly for custom
  # protocols, in windows, this is not the case. See #432
  if (normalizePath("s3n://", mustWork = FALSE) == "s3n://") {
    normalizePath(path, mustWork = FALSE)
  } else {
    # for windows users
    if (substr(path,1,6)=='s3n://') {
      return(path) # to cater for an S3 path
    } else {
      return(normalizePath(path, mustWork = FALSE)) # to still handle relative paths
    }
  }
}
```

**Comment by javierluraschi** [comment]
Thank you @niklasvm! Yes, I didn't mean to not return anything for windows, but rather, avoid normalizing the path in windows. We could certainly try other alternatives but I wonder if we can skip normalizePath in windows entirely. Would you mind giving the new fix a try?

The reason why `normalizePath` was introduced was to handle relative paths in linux-like systems, so if relative paths work fine in local mode under windows, then the fix as it is should be enough. Otherwise, we can find a way to support relative paths appropriately in windows.

**Comment by niklasvm** [comment]
Hi @javierluraschi. Thanks for the fix.

I can now successfully read a csv/parquet file from S3. I am also able to read csv/parquet from local **BUT** only using an *absolute path*. When using a path with a tilde it fails.

For example, the following works correctly:
```{r}
spark_normalize_path('C:/Users/user1/Documents/a csv file.csv')
```
but
```{r}
spark_normalize_path('~/a csv file.csv')
```
just returns ~/a csv file.csv which is then incorrectly appended to the current working directory and the spark_read_csv/spark_read_parquet functions fail.
