### ISSUE TITLE
read sparkdataframes created with sparkr

### ISSUE THREAD

**Issue by joscani** [rstudio/sparklyr#476]
Hi everyone. I want to use sparkr and sparklyr together in my local machine, but
I can't read  a sparkdataframe using src_tbls() . 

Here is my code. Spark version has been installed using spark_install from sparklyr. Any idea? thanks

```
Sys.setenv(SPARK_HOME="/home/jose/.cache/spark/spark-1.6.2-bin-hadoop2.6/" )
library(SparkR,lib.loc = "/home/jose/.cache/spark/spark-1.6.2-bin-hadoop2.6/R/lib/")

sc <- sparkR.init()
sqlContext <- sparkRSQL.init(sc)
df <- createDataFrame(sqlContext, faithful)
showDF(df)

# Start sparklyr over the same spark version
library(sparklyr)
library(dplyr)
sc <- spark_connect(master = "local", version = "1.6.2")

src_tbls(sc)
character(0)
```

**Comment by javierluraschi** [comment]
Hi @joscani! `sparklyr` and `SparkR` use different backends and are quite different, for instance, `SparkR` stores RDDs as R binaries while `sparklyr` stores them as JVM binaries (through Scala). Therefore, there is currently no direct way to read dataframes directly and any workaround will have a memory transformation cost.

However, to shared them indirectly you can definitely persist them in SparkR and reload them in sparklyr, say, by persisting them as parquet file.

Alternatively, this could also be accomplished through Hive but it will have the same penalty. Through, Hive, you would have to:
 1. Connect to the same Spark cluster (`master=local` won't work here since each time this is executed or `sparkRSQL.init` is run, a new cluster is created), you might want to create a local cluster explicitly using `SPARK_HOME/sbin/start-master.sh` instead.
 2. Potentially, call `registerTempTable` from `SparkR` and then read this table from Hive using `sparklyr` in the same session. This is unknown territory since I don't know of anyone successfully connecting both.

**Comment by javierluraschi** [comment]
Acceptable answer? Closing but if not, will reopen.
