### ISSUE TITLE
error when creating a spark connection in windows 7

### ISSUE THREAD

**Issue by FrissAnalytics** [rstudio/sparklyr#48]
Hi,

after successfully installing the latest RSTUDIO dev version (0.99.1246), and installing the `sparklyr` package I get an error when I try to create a spark connection:

```r
library(sparklyr)
library(dplyr)
sc <- spark_connect(master = "local")
```

results in
```r
Error: java.lang.RuntimeException: java.lang.RuntimeException: The root scratch dir: /tmp/hive on HDFS should be writable. Current permissions are: rw-rw-rw-
	at org.apache.hadoop.hive.ql.session.SessionState.start(SessionState.java:522)
	at org.apache.spark.sql.hive.client.ClientWrapper.<init>(ClientWrapper.scala:204)
	at org.apache.spark.sql.hive.client.IsolatedClientLoader.createClient(IsolatedClientLoader.scala:238)
	at org.apache.spark.sql.hive.HiveContext.executionHive$lzycompute(HiveContext.scala:218)
	at org.apache.spark.sql.hive.HiveContext.executionHive(HiveContext.scala:208)
	at org.apache.spark.sql.hive.HiveContext.functionRegistry$lzycompute(HiveContext.scala:462)
	at org.apache.spark.sql.hive.HiveContext.functionRegistry(HiveContext.scala:461)
	at org.apache.spark.sql.UDFRegistration.<init>(UDFRegistration.scala:40)
	at org.apache.spark.sql.SQLContext.<init>(SQLContext.scala:330)
	at org.apache.spark.sql.hive.HiveContext.<init>(HiveContext.scala:90)
	at org.ap
```

if I run the last command again i.e. `sc <- spark_connect(master = "local")` the code executes without generating an error. However, when I then try to read for instance the iris set I get another error:

```r
iris_tbl <- copy_to(sc, iris)
Error: Unable to retreive a spark_connection from object of class NULL
```

What can I do to fix this issue?

I'm running Windows 7 and my sessionInfo() is this:

``` r
sessionInfo()
R version 3.3.0 (2016-05-03)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows 7 x64 (build 7601) Service Pack 1

locale:
[1] LC_COLLATE=Dutch_Netherlands.1252  LC_CTYPE=Dutch_Netherlands.1252    LC_MONETARY=Dutch_Netherlands.1252 LC_NUMERIC=C                      
[5] LC_TIME=Dutch_Netherlands.1252    

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] dplyr_0.5.0    sparklyr_0.2.7

loaded via a namespace (and not attached):
 [1] Rcpp_0.12.5     sparkapi_0.2.0  digest_0.6.9    withr_1.0.1     assertthat_0.1  rappdirs_0.3.1  R6_2.1.2        DBI_0.4-1       git2r_0.15.0    magrittr_1.5   
[11] httr_1.2.0      curl_0.9.7      config_0.1.0    devtools_1.11.1 tools_3.3.0     parallel_3.3.0  yaml_2.1.13     rsconnect_0.4.3 memoise_1.0.0   tibble_1.0 

```

**Comment by javierluraschi** [comment]
@FrissAnalytics we based our QA for this first release in Windows 10; therefore, that would be a well-known path to get sparklyr running on windows. However, to unblock yourself in Win7, please try running:

`c:\tmp\hadoop\bin\winutils.exe chmod 777 c:\tmp\hive`

and to validate this has worked, run:

`c:\tmp\hadoop\bin\winutils.exe ls c:\tmp\hive`

and validate the permissions change to `drwxrwxrwx`.

**Comment by javierluraschi** [comment]
@FrissAnalytics also, which version of Windows 7 are you running? x64? Ultimate?

**Comment by FrissAnalytics** [comment]
Hi,

when I run the two commands you suggest via cmd on Windows I get an error message after the second command:

`FindFileOwnerAndPermission error (1789): The trust relationship between this workstation and the primary domain failed.`

I'm running Windows 7 professional, system-type: 64-bit, processor: Intel Core i7, with 8 GB RAM.

**Comment by javierluraschi** [comment]
Is your machine part of a windows domain? There might be restrictions from your system administrator in place.

Regardless, this sounds like this problem: http://stackoverflow.com/questions/37796004/winutils-exe-chmod-command-doesnt-set-permission

Which is an issue from running spark in Windows rather than the `sparklyr` package. That said, you might be able to unblock this by changing the permissions of that directory manually. Would you mind trying changing the permissions from the Windows UI and sharing the results?

**Comment by FrissAnalytics** [comment]
unfortunately it still doesn't work. I've manually set all permissions for both the hadoop and hive folders in the tmp folder by right clicking on the folders, going to Properties, go to Security and subsequently set all Permissions (allowed all items). Tomorrow I'll talk to someone from the system administration at my company to see if they know more. If I know what it is I'll post the solution here!

**Comment by javierluraschi** [comment]
Sounds good. BTW. Are you planning to connect into an Spark cluster that already exists in your organization? If you are connecting into an existing cluster, you would not have to figure out this issue, instead, you would set `spark_connect(master = "<admin-provided-master-url">)`. Otherwise, if you are planning to start with a local cluster then this issue still would have to get sorted out.

**Comment by javierluraschi** [comment]
@FrissAnalytics several fixes to improve install and use in windows have been checked-in. Please try the following to attempt to get past this error:

1. Upgrade to the latest version of sparklyr, instructions here: https://github.com/rstudio/sparklyr#installation
2. Rerun `spark_install()`, optionally, specify the `version` parameter.
3. Optional, but recommended, delete the `c:\users\<user-name>\AppData\local\Temp` directory, not only the contents but the actual `Temp` directory as well.
4. Connect again as `sc <- spark_connect(master = "local")`.
5. If something fails, please run `spark_log(sc)` and post the log in here.

The fix that was performed in `0.2.22` that might solve this particular "(1789) trust relationship" problem was moving the hadoop and hive directories out of `c:\tmp` into user directories since this location is not writable in all configurations and could also be blocked by admin settings.

**Comment by javierluraschi** [comment]
@FrissAnalytics this issue has been inactive for a few days, closing. However, if you find that the above instructions do not resolve this problem, please reactivate to recommend a different approach.

**Comment by HerveMignot** [comment]
I also have this issue when my PC is not able to reach the Windows Domain Controller. As a workaround, starting my VPN to reach it solves the problem. Once the Spark Context is started, you don't need your VPN to be up...

**Comment by topherdea** [comment]
I saw from a different posting this worked:
config <- spark_config()
config[["sparklyr.defaultPackages"]] <- NULL
sc <- spark_connect(master = "local", config = config)
