### ISSUE TITLE
Add support for variable transformations in ml_* formulas

### ISSUE THREAD

**Issue by sdanielzafar** [rstudio/sparklyr#554]
Currently Sparklyr only accepts simple formulas in ml_linear_regression(). Operators such as ':' should be supported following the convention of lm(). SparkR has this functionality. Interaction terms are crucial to econometric modeling and this addition will help pave the way for moving larger econometric analysis into Spark.

**Comment by sdanielzafar** [comment]
I don't mind working on this issue myself if someone wants to reach out to me at daniel.zafar at gmail.com so I can ask questions.

**Comment by kevinykuo** [comment]
We could expand https://github.com/rstudio/sparklyr/blob/master/R/formulas.R or maybe leverage the Scala code [here](https://github.com/apache/spark/blob/master/mllib/src/main/scala/org/apache/spark/ml/feature/RFormulaParser.scala) and [here](https://github.com/apache/spark/blob/master/mllib/src/main/scala/org/apache/spark/ml/feature/RFormula.scala), though I'm guessing there was a reason to not wrap the latter to begin with.

@kevinushey thoughts?

**Comment by kevinushey** [comment]
One of the main benefits of having the formula parser live in R code is that we can rely on R's own formula parser (that is, `stats::terms()`), which would in the future allow us to use arbitrary expressions in formulas.

**Comment by sdanielzafar** [comment]
Ah, so what should be done next?

**Comment by kevinushey** [comment]
Unfortunately implementing this will require quite a bit of work yet -- the simplest interim solution would be to just manually generate interaction columns in your dataset, and use those in the model fitting routines.

The overarching issue is that Spark's model fitting routines at their base have no concept of interaction terms; they just have input columns and output columns. This implies that, to support interaction terms, we'd have to:

1. Generate a new column representing the interaction of the two input columns,
2. Pass that along to the associated model fitting routine (as a 'feature'),
3. Make sure we do all the book-keeping correctly in the various downstream methods (`summary()`, `predict()`, etc.)

Supporting this really implies having support for features as arbitrary transformations of the input columns. (Aside: since an interaction effect is really just a specialized kind of transformation of two columns, it would make sense to get the general framework right when getting this to work)

We actually already do something like this for categorical variables -- currently, this is done by generating dummy variables for each category (each as a new column in the input dataset) with the related housekeeping; it'd be nice if we could make this all a bit more generic.

**Comment by kevinykuo** [comment]
Will keep an eye on these: https://issues.apache.org/jira/browse/SPARK-18569?jql=text%20~%20%22r%20formula%22
https://issues.apache.org/jira/browse/SPARK-18570?jql=text%20~%20%22r%20formula%22

**Comment by kevinykuo** [comment]
This has been implemented in devel. We now use Spark's `RFormula` interface. https://spark.apache.org/docs/latest/api/scala/index.html#org.apache.spark.ml.feature.RFormula
