### ISSUE TITLE
sparkhello: launch 'sparklyr::compile_package_jars()' download spark-1.5.2-bin-hadoop-2.6.tgz

### ISSUE THREAD

**Issue by Vonisoa** [rstudio/sparklyr#576]
Hello, I would try the sparkhello but when I launch
`sparklyr::compile_package_jars()`
it directly download spark-1.5.2-bin-hadoop-2.6.tgz instead I already have spark-2.1.0-bin-hadoop2.7 installed. Can anyone tell me where I did wrong?

**Comment by javierluraschi** [comment]
@Vonisoa could you share the output of `sparklyr::compile_package_jars()`? Which `sparklyr` version which operating system? Thanks!

**Comment by javierluraschi** [comment]
@Vonisoa Right, `compile_package_jars` does download several versions of Spark since it needs to compile against multiple versions to allow your extension to be deployed against several Spark versions.

That said, you could potentially have an extension that supports a subset of the Spark versions `sparklyr` supports. To do this run:

```
compile_spec <- spark_default_compilation_spec()
```

Modify `compile_spec` to remove the versions that you wish to not support, then rebuild using

```
compile_package_jars(spec = compile_spec)
```

Closing since this issue was more of a question than a change request.

**Comment by harryprince** [comment]
Hope to make specific scala home easier
