### ISSUE TITLE
error in Sparklyr after updating it

### ISSUE THREAD

**Issue by Venkatraman92** [rstudio/sparklyr#586]

**Comment by Venkatraman92** [comment]
Error : object 'db_data_type' not found whilst loading namespace 'sparklyr'
Error: loading failed
Execution halted

**Comment by kevinykuo** [comment]
See https://github.com/rstudio/sparklyr/issues/583

**Comment by javierluraschi** [comment]
@Venkatraman92 Can you try with the latest version, PR got merged a couple hours ago.

**Comment by am9090** [comment]
I have the same error I have installed 0.5.3? is that the latest

**Comment by javierluraschi** [comment]
@am9090 This is a breaking changed introduced in `dplyr`, I would recommend uninstalling `dplyr` and installing `dplyr` again from CRAN instead.

**Comment by am9090** [comment]
I tried that but still gives me that error

**Comment by javierluraschi** [comment]
@am9090 you might need to restart your rsession as well. The combination `dplyr` and `sparklyr` while installed from CRAN should work as appropriate since nothing has changed in a month or so. Therefore, there is probably something stagnant in your system, try the uninstall/restart/install `dplyr` combination.

Otherwise, `dplyr` and `sparklyr` isntalled from github should also work now.

Let us know what you find.

**Comment by javierluraschi** [comment]
@Venkatraman92 @am9090 Is the install looking good now? Otherwise, closing this issue.
