### ISSUE TITLE
Problem reading NULL values in external Hive tables

### ISSUE THREAD

**Issue by Chris-Engelhardt** [rstudio/sparklyr#606]
I have saved in an external database a Hive table. This table has columns containing known NULL values. When I try to read in columns containing NULLS, they are represented in unexpected ways. For example, NULLs in a tinyint column are read as 80 (variable type raw), whereas NULLs in a bigint column are imported as -9.223372e+18 (variable type dbl). I would have expected NULLs to be imported as NAs, as they are with CSVs, but this is not the case here.  

Some example code: 

library(sparklyr)
library(dplyr)

spark_config_op_medium <- function(spark_version = "1.6.0", ...){
  config <- sparklyr::spark_config()
  config$spark.executor.instances <- 8
  config$spark.executor.memory <- "30g"
  config$spark.executor.cores <- 5 
  sc <- sparklyr::spark_connect(master = "yarn-client", config = config, version = spark_version, ...)
  assign("sc", sc, envir = globalenv())
}

spark_config_op_medium()
tbl_change_db(sc, "db_name")
tmp <- tbl(sc, "db_table")

We are running Spark 1.6.0 on YARN using CDH and sparklyr version 0.5.3.9002. Any ideas what might be going on here?

**Comment by kevinushey** [comment]
My guess is that `NULL` is coming back as their associated minimum values (note that `0x80` would be expressed as `-127` within a signed 8-bit integer type). For `bigint`, we could definitely detect this minimum value and convert it to `NA` / `NaN`, but unfortunately R's `raw()` data type does not have an associated `NA` / missing value.

Part of this ugliness comes from a decision to deserialize these columns as vectors, rather than lists -- since R's primitive vectors cannot contain a 'null' value, there is ultimately a bit of loss of information here.

I think the solution for `BigInt`s is to ensure that we translate those minimum values to `NA`, but I'm not sure what should be done for `tinyint`. Perhaps those should instead be serialized as an R integer type, rather than raw?

**Comment by kevinushey** [comment]
The more nuclear option would be to have us de-serialize these as lists of length-one elements, whose value could then be `NULL`, but this is undesirable mainly because it has a catastrophic effect on deserialization performance.

**Comment by edgararuiz** [comment]
Hi @Chris-Engelhardt, when you pull this directly in the cluster, like via Hue, how are they displaying?

**Comment by Chris-Engelhardt** [comment]
@edgararuiz In Hue, they are displaying as NULL.

**Comment by edgararuiz** [comment]
Understood.  I know it won't solve the root cause, but wouldn't declaring the columns as just 'int' work?  That's how I declare mine and so far NULLs come across as NA's for me

**Comment by Chris-Engelhardt** [comment]
Yes. That's a good short-term solution, and is how I resolved a similar bug with Microsoft R server (there, I needed to cast tinyint to int w/in a sql query).
