### ISSUE TITLE
spark_write_parquet() aborts for large datasets

### ISSUE THREAD

**Issue by richierocks** [rstudio/sparklyr#616]
To reproduce:

```r
library(dplyr)
library(sparklyr)

n <- 1e7
d <- data_frame(
  x1 = runif(n),
  x2 = runif(n),
  x3 = runif(n),
  x4 = runif(n),
  x5 = runif(n),
  x6 = runif(n),
  x7 = runif(n),
  x8 = runif(n),
  x9 = runif(n),
  x10 = runif(n),
  x11 = runif(n),
  x12 = runif(n),
  x13 = runif(n),
  x14 = runif(n),
  x15 = runif(n),
  x16 = runif(n)
)
sc <- spark_connect("local")
d_tbl <- copy_to(sc, d)

spark_write_parquet(d_tbl, "test_parquet")
## Error: org.apache.spark.SparkException: Job aborted.
```

(Vary `n` and the number of columns as necessary.)

**Comment by javierluraschi** [comment]
Sounds like an issue in Spark, but worth investigating under `sparklyr`.

**Comment by javierluraschi** [comment]
Looks to me expected given constrained resources in different systems, for instance, I would get a `Job aborted.` with logs pointing to memory:

```
 Error: org.apache.spark.SparkException: Job aborted due to stage failure: Task 13 in stage 66.0 failed 1 times, most recent failure: Lost task 13.0 in stage 66.0 (TID 79, localhost): java.lang.OutOfMemoryError: GC overhead limit exceeded
```

With the script running for `n <- 1e6`, I can copy but then `spark_write_parquet()` fails.

The problem seems to be (see https://issues.apache.org/jira/browse/PARQUET-222), that the parquet writer opens a file + buffer for each column, which under memory pressure could fail to accommodate even for a few columns.

I think is safe to close this one, hopefully, this will get optimized in Spark at some point.
