### ISSUE TITLE
glimpse doesn't work

### ISSUE THREAD

**Issue by kevinykuo** [rstudio/sparklyr#621]
```
sc <- spark_connect(master = "local")
iris_tbl <- copy_to(sc, iris)
glimpse(iris_tbl)
# Observations: 150
# Variables: 5
# Error in if (width[i] <= max_width[i]) next : 
#   missing value where TRUE/FALSE needed
```

**Comment by kevinushey** [comment]
It looks like the issue here (if I understand correctly) is that we dispatch to `glimpse.tbl` rather than a more appropriate method.

@hadley, our Spark tables have class:

```
Browse[3]> class(x)
[1] "tbl_spark" "tbl_sql"   "tbl_lazy"  "tbl"   
```

Is there some package that should be providing a `glimpse` method for `tbl_sql`s or `tbl_lazy`s? Or do we need to just implement `glimpse` ourselves for `tbl_spark`s?

**Comment by kevinykuo** [comment]
Looking at `glimpse.tbl` I think it might work if we provide a `type_sum.tbl_spark` and request a change upstream to use `tbl_vars()` instead of `names()` around https://github.com/tidyverse/tibble/blob/81ea9560bfe9abc34210484720c13688ce3e1589/R/glimpse.R#L46-L47

**Comment by kevinushey** [comment]
That won't be quite enough -- the `vapply()` call would need to be changed too, as that will operate on the `src` and `ops` variables in the table object. I think there needs to be a separate method altogether for `tbl_sql`s.

**Comment by kevinykuo** [comment]
@kevinushey right, just realized `type_sum` is applied to each column...

**Comment by hadley** [comment]
`tbl_sql()` should really get a glimpse method — can you please file an issue in dplyr?

**Comment by kevinushey** [comment]
Will do!
