### ISSUE TITLE
dplyr renaming of duplicate columns breaks joins

### ISSUE THREAD

**Issue by kevinykuo** [rstudio/sparklyr#638]
Can we catch this with schema sanitation or is this mechanism entirely in dplyr/dbplyr?

```
sc <- spark_connect(master = "local")
iris_tbl <- copy_to(sc, iris)
iris_tbl %>% inner_join(iris_tbl, by = "Sepal_Length")
# Error: org.apache.spark.sql.AnalysisException: cannot resolve '`Sepal_Width.x`' given input columns: [Petal_Length.y, Species.y, Sepal_Length, Petal_Width.x, Petal_Length.x, Sepal_Width.x, Sepal_Width.y, Petal_Width.y, Species.x]; line 1 pos 0
# at org.apache.spark.sql.catalyst.analysis.package$AnalysisErrorAt.failAnalysis(package.scala:42)
```

Possibly relevant: https://issues.apache.org/jira/browse/SPARK-5632

**Comment by javierluraschi** [comment]
Don't remember the details, but I believe self-joins have limits in `Spark 1.6.X`. We used to have a nice error message saying something like "This feature is not supported in Spark 1.6.X, please use Spark 2.X" but we removed this when we simplify our `dplyr` implementation (much of the overrides are now implemented in `dbplyr`).

Therefore, the best we could do would be to bring back the error message. If you want to overcome this, try Spark 2.0. I'll leave this issue open since it would be good to bring back the error message if this can be done in a simple way.

**Comment by javierluraschi** [comment]
No great mechanism to override this apart from overriding all joins again and subclassing the connection, I think this has the potential to create more problems for a bit of error message improvements. Closing.

**Comment by benoitrolland** [comment]
There is a workaround by [JohnMount](https://github.com/JohnMount) in issue [1594](https://github.com/sparklyr/sparklyr/issues/1594) description: 
Replace the join suffix keys to not include dots on colnames: 
iris_tbl %>% inner_join(iris_tbl, by = "Sepal_Length", c("_x", "_y"))
