### ISSUE TITLE
Can't create confusion matrix using `table()` with sdf objects. 

### ISSUE THREAD

**Issue by JosiahParry** [rstudio/sparklyr#67]
This is because I cannot select certain columns of a spark dataframe.

**Comment by JosiahParry** [comment]
I can create the confusion matrix after using `collect()`and creating a local df. is this the best way to do it?

**Comment by javierluraschi** [comment]
@JosiahParry If the input data to the confusion matrix is small enough to fit into your machine, then, yes, that's a good way to do it: `collect()` then build the confusion matrix.

However, if the input data is not small enough to fix into your machine, let us know to help unblock this.

Some more context: Spark provides a way to calculate a confusion matrix (see https://spark.apache.org/docs/2.0.0-preview/api/scala/index.html#org.apache.spark.mllib.evaluation.MulticlassMetrics) on their original RDD API to which we have not provided wrappers around since we are focusing on the newer DataFrame API, but we could consider extending this wrappers at some point. More about this topic here: https://spark.apache.org/docs/latest/mllib-guide.html
