### ISSUE TITLE
How to get the top nth value in sparklyr?

### ISSUE THREAD

**Issue by 3zhang** [rstudio/sparklyr#699]
In dplyr, I can achieve this by "nth" function:

```
iris_tbl=tbl_df(iris)
iris_tbl %>% group_by(Species) %>% 
  summarise(TOP_1=nth(Sepal.Width,1,order_by=desc(Sepal.Width)),
            TOP_2=nth(Sepal.Width,2,order_by=desc(Sepal.Width)),
            TOP_3=nth(Sepal.Width,3,order_by=desc(Sepal.Width)))
```

How can I achieve the same thing in sparklyr?

**Comment by edgararuiz** [comment]
Hi, try using the PERCENTILE Hive UDF

**Comment by 3zhang** [comment]
@edgararuiz Thank you. Could you please also take a look at this? https://github.com/rstudio/sparklyr/issues/689

**Comment by chezou** [comment]
@3zhang Is it completely separate issue, right? Could you close this issue, if your problem in this issue was solved.

**Comment by 3zhang** [comment]
@chezou I don't know how to close this issue.

**Comment by chezou** [comment]
It seems [this comment](https://github.com/rstudio/sparklyr/issues/699#issuecomment-303670457) solves your problem. Of course, there might be some more question about it; otherwise, you can close pushing "Close issue" button.

![image](https://cloud.githubusercontent.com/assets/916653/26618527/a2b51cba-4615-11e7-89bb-38aefa3a5ff1.png)
