### ISSUE TITLE
Function that returns tbl_spark from Spark SQL query

### ISSUE THREAD

**Issue by kevinykuo** [rstudio/sparklyr#742]
`DBI::dbGetQuery()` collects, and it may be useful to have a function that returns a `DataFrame`.

**Comment by randomgambit** [comment]
@kevinykuo that is interesting. I was playing around with `dbGetQuery()`.

Is there a way to store the output of the query into a **spark dataframe** (not the R memory) that can accessed later on with sparklyr?

**Comment by randomgambit** [comment]
@kevinykuo  what about 
```
DBI::dbSendQuery(sc, "CREATE TABLE mytable AS SELECT * FROM df)
new_df <- tbl(sc, "mytable")
```

**Comment by javierluraschi** [comment]
@kevinykuo Right now that would be `spark_session(sc) %>% invoke("sql", "SELECT 1")`, would help to know what you where trying to do that made you consider this function. There is also `tbl(sc, sql("SELECT 1"))`.

**Comment by kevinykuo** [comment]
@javierluraschi this is it. It'd be nice to include under "Direct Spark SQL commands" in the [cheat sheet](http://spark.rstudio.com/images/sparklyr-cheatsheet.pdf) @edgararuiz ;)

**Comment by saurfang** [comment]
This is very useful in large dataset use cases, which should be fairly common in enterprise settings. Dataset is usually too big to fit in memory so `dbGetQuery` is not appropriate. One would also almost never start an analysis or model training from an entire Hive table. Tables are usually partitioned by some datetime columns as they are incrementally ETLed into data warehouse.

`spark_read_table(sc, 'my_table')` can be harmful since accidentally printing it would ask the driver to scan through all the historical partitions and could potentially overload metastore. It is common to base an analysis off a SQL query like 

```sql
SELECT a.column1, a.column2, ..., b.column1, ..., b.column9 
FROM 
  some_big_table a 
JOIN 
  another_big_table b 
ON 
  a.ds = '2018-05-30' AND 
  b.ds BETWEEN '2017' AND '2018' AND 
  a.id_user = b.id_user
WHERE
  a.cohort IN ('A', 'C')
```

Last but not least, while dplyr promotes a very readable and functional way of constructing dataframe off a raw table in database, SQL is just a much more ubiqutous language. If a company has people working in R/Python/Scala/SQL etc at the same time, chances are there are a lot of SQL that can be reused. Technically all of these can be achieved via creating a view but in practice it is an extra friction, and we often want these "views" to be temporary in session.

**Comment by kevinykuo** [comment]
@saurfang Could you elaborate why `tbl()` doesn't suffice for your use case?

**Comment by saurfang** [comment]
It totally does and I was just voicing that it is not the most straightforward way possible given how common I think this is used. I don't believe any of the Sparklyr documentation explicitly mentions it. The reading data section reads data either from a location on HDFS or copies data from R to the Spark cluster. Considering it is very easy to use in native Spark i.e. `sparkSession.sql("...")` and one of the first things mentioned in [SparkSQL documentation](https://spark.apache.org/docs/latest/sql-programming-guide.html#running-sql-queries-programmatically), I expect there is either a wrapper function like `sparklyr::spark_sql(sc, "sql")` or `tbl(sc, sql("..."))` mentioned in the sparklyr documentation.

**Comment by chappers** [comment]
I agree with saurfang, this kind of information should definitely be somewhere obvious in the docs -
