### ISSUE TITLE
gapply/group operation support for sparklyr

### ISSUE THREAD

**Issue by statmatt** [rstudio/sparklyr#770]
sparklyr needs to support an alias/synonym for the SparkR::gapply functionality. sparklyr::spark_apply seems to be synonymizing SparkR::dapply, but this is not sufficient. 

As an example (cannot provide code example here), let's say I want to run GLM models on specific groups of data indexed by columns in my data frame ... with SparkR::gapply, I can write a function to perform my modeling on each group separately, then use gapply to run models within groups.

**Comment by javierluraschi** [comment]
Investigated this one, was hoping that with the by-row functionality `spark_apply` provides, we would be closer to provide by-group functionality.

In other interfaces, say `sparkR`, this is implemented in [gapply](https://github.com/apache/spark/blob/39e2bad6a866d27c3ca594d15e574a1da3ee84cc/sql/core/src/main/scala/org/apache/spark/sql/api/r/SQLUtils.scala#L195-L204) by calling [DataSet.groupBy](https://spark.apache.org/docs/2.0.2/api/scala/index.html#org.apache.spark.sql.Dataset) which would return a [RelationalGroupedDataset](https://spark.apache.org/docs/2.0.2/api/scala/index.html#org.apache.spark.sql.RelationalGroupedDataset), which runs [flatMapGroupsInR](https://github.com/apache/spark/blob/beed5e20af0a3935ef42beb3431c8630599bf27f/sql/core/src/main/scala/org/apache/spark/sql/RelationalGroupedDataset.scala#L415-L438) and provides a custom Catalys Plan through [FlatMapGroupsInR](https://github.com/apache/spark/blob/bb823ca4b479a00030c4919c2d857d254b2a44d8/sql/catalyst/src/main/scala/org/apache/spark/sql/catalyst/plans/logical/object.scala#L428-L454).

We will need to schedule some time to get implemented since it's not an incremental jump over `spark_apply`.

Marking as Feature Request and moving out of `sparklyr 0.6`, the good news,  we would need this to fully support `dplyr::do` already being tracked here: https://github.com/rstudio/sparklyr/projects/1
