### ISSUE TITLE
Support for decimal separator (comma or period), skip lines and nrows ?

### ISSUE THREAD

**Issue by hiltonmbr** [rstudio/sparklyr#83]
Dear @javierluraschi,

I would like to know if is possible to implement the followings options in spark_read_csv() function:

dec = '.' or ',' => for numerical decimal separator (period by default)
skipline = FALSE or integer => for skip lines during csv read
nrows =  FALSE or integer => for select the number of rows to read

I think these options could help us to handle with different kinds of csv datasets.

Thanks.

**Comment by javierluraschi** [comment]
Currently we have implemented reading/writing CSVs using Databricks CSV package (https://github.com/databricks/spark-csv). It is my understanding that the options you describe are not supported yet. I'll keep this issue open to explore a more comprehensive approach. In the meantime, here are a couple ideas that could help workaround this issue:

1. Fix the numeric field after reading from CSV.
2. Use dplyrs filter to remove unwanted rows.
3. Use `spark_read_csv(memory = FALSE)` since this would avoid reading and loading into memory eagerly, then you can use `collect(table, n=100)` to read `100` rows for this example.

**Comment by hiltonmbr** [comment]
To clarify my point, I have a large CSV file with header contains the description of variables instead of right variable names. I have tried the following:
First, read CSV without the header:

df <-  spark_read_csv(sc,name="mytable",path=myfile, 
                     header=FALSE,memory=FALSE)
df

Source:   query [?? x 28]
Database: spark connection master=local[*] app=sparklyr local=TRUE
       _c0                 _c1                 _c2          _c3
       <int>              <int>                <int>        <int>
1     110028          26417                   0           10
2     110020          15890                   0           10
3     110009          20109                   0           10

On the other hand, I have a vector including correct names of the variables :
v <- c("name1","name2", ...  )

Thus, I've tried set colnames of Spark data frame without collect it using:
colnames(df) <- v
It returns a error
Therefore, how to set all column names without collect spark data frame ? I cannot collect it because the file is large and does not fit in RAM memory. Any ideias?

**Comment by javierluraschi** [comment]
Closing this one with two references:

1. Spark 2.2 supports a bit more options, see: https://spark.apache.org/docs/2.2.0/api/java/org/apache/spark/sql/DataFrameReader.html#csv but not quite what this issue requests
2. `sparklyr 0.7` will support `spark_read_text()` and `spark_write_text()`, in combination with `dplyr` or `spark_apply()` I'm hoping we can split lines and convert types as needed. See https://github.com/rstudio/sparklyr/pull/913.
