### ISSUE TITLE
Consider modifications to spark_apply group_by API

### ISSUE THREAD

**Issue by kevinykuo** [rstudio/sparklyr#842]
For discussion... here are some ideas I have from playing with https://github.com/rstudio/sparklyr/pull/833

cc @javierluraschi @statmatt

1. The key(s) should come first in arguments for `f`. I think this is more natural.
2. Append grouping columns to resulting DataFrame by default. In practice they're almost always needed and users can easily deselect/rename otherwise.
3. Support grouping by multiple columns.

Sample test for these requirements:

```
s <- spark_apply(
  mtcars_tbl,
  function(cyl, gear, d) lm(mpg ~ disp, d)$coefficients[["(Intercept)"]],
  names = c("intercept"),
  group_by = list("cyl", "gear")
) %>% collect()

r <- mtcars %>%
  tidyr::nest(-cyl, -gear) %>%
  mutate(model = purrr::map(data, ~lm(mpg ~ disp, data = .)),
         intercept = purrr::map_dbl(model, function(x) x$coefficients[["(Intercept)"]])) %>%
  select(cyl, gear, intercept)

expect_equal(s, r)
```

4. Enforce function signature of `f` to be consistent with number of grouping columns. The user can give either 1 argument (for the data) or *n* where *n = number of grouping columns + 1*. So this would be OK:

```
s1 <- spark_apply(
  mtcars_tbl,
  function(cyl, gear, d) lm(mpg ~ disp, d)$coefficients[["(Intercept)"]],
  names = c("intercept"),
  group_by = list("cyl", "gear")
) %>% collect()

s2 <- spark_apply(
  mtcars_tbl,
  function(d) lm(mpg ~ disp, d)$coefficients[["(Intercept)"]],
  names = c("intercept"),
  group_by = list("cyl", "gear")
) %>% collect()

expect_equal(s1, s2)
```

But this would not:

```
expect_error(
  spark_apply(
    mtcars_tbl,
    function(cyl, d) lm(mpg ~ disp, d)$coefficients[["(Intercept)"]],
    names = "intercept",
    group_by = list("cyl", "gear")
  ),
  "'f' has incorrect number of arguments"
)
```

**Comment by statmatt** [comment]
@javierluraschi @kevinykuo comments below. Thanks for jumping on this guy so quickly.

`The key(s) should come first in arguments for f. I think this is more natural.`

Agreed, and this is consistent with the SparkR API as well.

`Append grouping columns to resulting DataFrame by default. In practice they're almost always needed and users can easily deselect/rename otherwise.`

This is possible, but it's not necessarily bad to allow the user to format the key columns as part of the group by operation (or potentially omit them). The R version of groupBy has some nice qualities that differentiate it from the Scala or Python groupBys (the ability to return a dataframe, and not just one row in a dataframe is great), so I think you're in unique enough territory you could do it either way

`Support grouping by multiple columns.`

Absolutely. This is a requirement (probably should have been explicit on this is the original ticket).

`Enforce function signature of f to be consistent with number of grouping columns. The user can give either 1 argument (for the data) or n where n = number of grouping columns + 1. So this would be OK:`

Not sure on this one. A function of two arguments (first is a vector or df of key values, second is the dataframe) is what's currently established. You could certainly do it this way, but what's the usability advantage?

**Comment by javierluraschi** [comment]
I really like function arguments order to stay consistent between `group_by = NULL` and `group_by = "column_name"), but (2) adding grouping columns and (3) grouping by multiple columns makes sense to me.
